osx_image: xcode10.1
language: swift
script:
  - xcodebuild -project swiftness.xcodeproj -scheme swiftness-osx -destination platform\=macOS build
  - xctool -project swiftness.xcodeproj -scheme swiftness-osx-tests -destination platform\=macOS test

